services:
  sonarqube:
    image: sonarqube:25.6.0.109173-community
    container_name: sonarqube
    depends_on:
      - sonar_db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar_db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
      SONAR_SEARCH_JAVA_OPTS: "-Xms2g -Xmx2g"
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
    ports:
      - "9000:9000"
    volumes:
      - sonar-conf:/opt/sonarqube/conf
      - sonar-data:/opt/sonarqube/data
      - sonar-extensions:/opt/sonarqube/extensions
    restart: unless-stopped
    networks:
      - shared_network

  sonar_db:
    image: postgres:17
    container_name: sonar_db
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - sonar-postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - shared_network

networks:
  shared_network:
    driver: bridge

volumes:
  sonar-conf:
  sonar-data:
  sonar-extensions:
  sonar-postgres-data:
